### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by roedoejet** [dhdaines/ReadAlong-Studio#7]
Very minor issue to follow the Canadian Translation Bureau [guidelines](http://www.btb.termiumplus.gc.ca/tcdnstyl-srch?lang=fra&srchtxt=indigenous&cur=1&nmbr=4&lettr=4&info0=4.11) for capitalizing the word 'Indigenous' in the repo description. Currently: "Audiobook alignment for North American indigenous languages"

> Capitalize the singular and plural forms of the nouns Status Indian, Registered Indian, Non-Status Indian and Treaty Indian, as well as the adjectives Indigenous and Aboriginal, when they refer to Indigenous people in Canada.

- Indigenous person (one individual)
    * Example: Any Indigenous person in Alberta is eligible under this program.
- Indigenous persons, Indigenous people (more than one person)
    * Example: The conference could not have succeeded without the help of almost a 
 thousand Indigenous people from all over Saskatchewan.
- Indigenous peoples (two or more Indigenous groups)
    * Example: Representatives from three Indigenous peoples were present.

**Comment by dhdaines** [comment]
Interesting! Was not aware of this style guideline but I am mostly writing
in French where the rules are different... will change it!

**Comment by roedoejet** [comment]
Also, coming back to this, we're not really specific to North America, right? How about "Audiobook alignment for Indigenous languages"

**Comment by dhdaines** [comment]
Good idea :)

Le mar. 8 oct. 2019, à 16 h 20, Aidan Pine <notifications@github.com> a
écrit :
