### ISSUE TITLE
Set root directory on coveralls

### ISSUE THREAD

**Issue by roedoejet** [dhdaines/ReadAlong-Studio#9]
Currently coveralls makes you go way deep down into the directory structure just to see the relevant files: 

![image](https://user-images.githubusercontent.com/14815080/65278557-3b5da380-dae1-11e9-886d-085c3d5414b2.png)

There's a way to set the root directory so that it does away with all those files and also let's you see each file's coverage. Right now it just says:

```SOURCE NOT AVAILABLE
The file "/home/travis/build/dhdaines/ReadAlong-Studio/readalongs/align.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.
```

I think the solution is [here](https://github.com/lemurheavy/coveralls-public/issues/886) and that if you're logged in as the owner (@dhdaines) you should see a somewhere to change the root.

**Comment by dhdaines** [comment]
Hi! I think I fixed it, can you check?

**Comment by roedoejet** [comment]
Great, ok I can see the file coverage now which is great. The folders aren't collapsing so maybe I either need to push another commit or it's a different issue. Thanks! I'll take another look on the next commit.
